version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[transformers]]
name = "prettier"
enabled = true